
export const especialidades = [
    "Anestesiología",
    "Cardiología",
    "Dermatología",
    "Endocrinología",
    "Gastroenterología",
    "Geriatría",
    "Ginecología",
    "Hematología",
    "Infectología",
    "Medicina general",
    "Nefrología",
    "Neumología",
    "Neurología",
    "Nutriología",
    "Obstetricia",
    "Oftalmología",
    "Oncología",
    "Ortopedia",
    "Otorrinolaringología",
    "Pediatría",
    "Psiquiatría",
    "Radiología",
    "Reumatología",
    "Traumatología",
    "Urología"
];
